### ISSUE TITLE
Crear exe para windows: ¿Qué esperas que suceda al dar doble click?

### ISSUE THREAD

**Issue by rctorr** [rctorr/FacturaElectronica#1]
Los usuario de _windows_ comentan que sería bueno tener un _exe_ para sólo hacer doble click, sin embargo un _exe_ del programa tal como está no creo que sea de mucha utilidad, lo siento!. El programa/script `renombracfd.py` está pensado para ser usado desde una ventana de comandos o algún otro programa que haga uso de el para automatizar algunas tareas. Esto me ha dado algunas ideas!

Entonces en la medida de lo posible me podrían ayudar a dar una respuesta a la siguiente pregunta:

**¿Qué esperas que suceda al dar doble click?**

_Gracias!_

**Comment by FalkZerd** [comment]
Hola, bueno cooperando un poco en el exe, quiza un poco de no programador como yo pueda decir algo interesante

Normalmente los xml te llegan a un correo predeterminado que tiene una carpeta de descargas asignado, tienes que arrastrar los archivos xml y organizarlo en tus carpetas, ya sea por fechas nombre de proveedores tipo de proveedor si es nota de credito si es exis doble-u o zeta, y quieras o no cada dia te pueden llegar varios asi que se vuelve una tarea diaria y tediosa

A mi, me gustaria que el exe buscara en una carpeta predeterminada los xml, los re nombrara y me los archivara en el lugar que me convenga, ya sea para después seleccionar y archivar como yo quiera o los deje archivados como sea el default del programa en la carpeta destino.

básicamente es una carpeta target que tiene varios tipos de archivo y una carpeta destino

Entre cosas interesantes que podria ayudar a evitar (que a mi me ocurren) 

-que haga un log con posibles dupliados
-Puedas programar la tarea (cada x hora guarda los xml)
- y aunque esto es extra y muchos ya lo hacen pero para los pobres diablos sin programas de contabilidad con valor un ojo de la cara, en un txt o excel que te guarde los datos reelevantes del xml.

Algo que tambien le daria un plus es: muchos archivos de estos te llegan en zip o comprimidos, seria interesante que analizara si hay archivos zip y extrajera los xml.

espero que mi comentario sea de utilidad

muchas gracias por el archivo, y tambien te deso lo mejor, si puedo ayudar en algo, no dudes en contactarme

Saludos

**Comment by rctorr** [comment]
Hola @FalkZerd vaya, creo que la respuesta va un poco lenta (dos años después) una disculpa por no decir un hola, pero un poco atareado con otras cosas, pero he entrado por acá porque ya tenemos un exe y con algunos agregados de algunos colaboradores, revisa un poco lo que se comenta en la página principal https://github.com/rctorr/FacturaElectronica y de verdad muchas gracias por tus aportes, has definido de forma muy clara no unos, si no un conjunto de necesidades que bien podríamos agregar en futuras versiones.

Muchas gracias por tus aportes y espero te sea de utilidad el nuevo EXE ;)
[renamecfd-win32.zip](https://github.com/rctorr/FacturaElectronica/files/398544/renamecfd-win32.zip)

Salu2+
