### ISSUE TITLE
Puedo crear una version en otros lenguajes?

### ISSUE THREAD

**Issue by kiramishima** [rctorr/FacturaElectronica#10]
Hola Ricardo Morales :joy: 

puedo basarme en tu codigo para crear una version en otros lenguajes ? :factory: 

Saludos

**Comment by rctorr** [comment]
Hola Kira de Morales :smile: :joy:

Claro, es software libre con licencia GNU v2, así que adelante

Salu2+

**Comment by Chemasmas** [comment]
Lo vamos a hacer en Java? O en Scala?

**Comment by kiramishima** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8063058-252551264_2-s1-v1.png?transparent=1&palette=1&width=246) en Scala 😄

**Comment by rctorr** [comment]
En Rust
