### ISSUE TITLE
Crear archivo bat y sh para ejecución rápida

### ISSUE THREAD

**Issue by rctorr** [rctorr/FacturaElectronica#2]
Crear un archivo bat y sh para que al dar doble click se ejecute el programa y renombre todos los archivos xml que estén en la misma carpeta.

**Comment by FalkZerd** [comment]
El bat
en bloc de notas guardando como .bat en la misma carpeta que el renamecfd.py 

```
@echo off
c:\Python27\pythonw renamecfd.py *.xml %*
pause
```

Saludos

**Comment by rctorr** [comment]
Este queda un poco obsoleto debido a que se ha creado tanto el instalador para windows, así como la versión ejecutable (EXE).

Gracias por todos sus aportes liberamos la versión 1.0.0-beta

Salu2+
