### ISSUE TITLE
Renombrar también el archivo PDF cuando éste exista con el mismo nombre que el xml

### ISSUE THREAD

**Issue by rctorr** [rctorr/FacturaElectronica#3]
Por lo general los archivos de facturación electrónica se reciben en pares, es decir, se recibe el archivo xml (que es en realidad el que cuenta para el sat) y un archivo pdf que es la representación impresa.

Entonces para tener la información homogénea, se propone renombrar tanto los archivos xml como el pdf correspondiente en caso de que exista.

**Comment by chichonline** [comment]
Hola rctorr esto que comentas es solo la recomendación o colocaste algún script para ello?

Las otras soluciones me han funcionado de maravilla.. saludos

**Comment by rctorr** [comment]
Hola @chichonline te comento que esta mejora ya la ha implementado @pixelead0 (muchas gracias Adan por tu colaboración, creo que ya te gustó python hehehe!)

@chichonline por favor has uso de código y si notas algún problema lo puedes comentar por acá ;)

Salu2+
