### ISSUE TITLE
Total de Impuestos y tipos de impuestos

### ISSUE THREAD

**Issue by pixelead0** [rctorr/FacturaElectronica#4]
En la etiqueta "cfdi:Impuestos" algunos CFDI's no contienen el atributo  "totalImpuestosTrasladados"
## Ejemplo:

``` .xml
    <cfdi:Impuestos>
        <cfdi:Traslados>
            <cfdi:Traslado importe="275.17" tasa="16.0" impuesto="IVA" />
        </cfdi:Traslados>
    </cfdi:Impuestos>
```

Y en otros casos los impuestos incluyen retenciones y traslado.
## Ejemplo:

``` .xml
  <cfdi:Impuestos totalImpuestosRetenidos="0.00" totalImpuestosTrasladados="0.00">
    <cfdi:Retenciones>
      <cfdi:Retencion importe="0.00" impuesto="ISR" />
    </cfdi:Retenciones>
    <cfdi:Traslados>
      <cfdi:Traslado importe="0.00" impuesto="IVA" tasa="16.00" />
    </cfdi:Traslados>
  </cfdi:Impuestos>
```

**Comment by rctorr** [comment]
Me parece que en el primer caso cuando no incluye totalImpuestosTrasladados podría corresponder a un xml mal formado según el Anexo 20. Necesario corroborar este punto ya que de ser así se podría hasta usar como posible forma de validar el xml.

**Comment by pixelead0** [comment]
**totalImpuestosTrasladados** Es opcional

ftp://ftp2.sat.gob.mx/asistencia_servicio_ftp/publicaciones/legislacion12/Anexo20_30122011.doc

totalImpuestosTrasladados

Descripción
Atributo opcional para expresar el total de los impuestos trasladados que se desprenden de los conceptos expresados en el comprobante fiscal digital.

Uso
opcional

**Comment by rctorr** [comment]
Adan

Gracias por el dato, más que confirmado!

Salu2+
