### ISSUE TITLE
CFDI sin serie ni folio

### ISSUE THREAD

**Issue by pixelead0** [rctorr/FacturaElectronica#6]
Existen algunos comprobantes sin numero de serie ni folio.

``` .python
           compAtrib = dict(comprobante.attributes.items())

            if  'serie' in compAtrib:
                self.atributos['serie'] = compAtrib['serie']
            else:
                self.atributos['serie'] = ""

            if  'folio' in compAtrib:
                self.atributos['folio'] = compAtrib['folio']
            else:
                self.atributos['folio'] = ""
```

**Comment by rctorr** [comment]
Muy cierto, ya que en el cfdi v3.2 la serie y folio son opcionales según el Anexo 20

**Comment by FalkZerd** [comment]
mmmm, como se pone en el archivo, ya intente casi de todo y se me acabaron las ideas (hasta cuide que estuviera alineado)

**Comment by rctorr** [comment]
Hola Falkzerd
A la alineación es importante y se debe realizar con espacios, si no es así no funcionará!

Hi Adan, te quería preguntar si podrías hacer el pull de tus modificaciones? gracias de antemano!

Salu2+
RT
